USE startersql;
-- SELECT * FROM USERS WHERE ID=3;
-- DELETE FROM USERS WHERE ID=3;
-- ALTER TABLE USERS ADD COLUMN is_active BOOLEAN DEFAULT TRUE;
-- ALTER TABLE USERS DROP COLUMN is_active;
-- UPDATE users SET salary=salary-10000 WHERE id>0 AND salary<70000;
SELECT * FROM users;